### ISSUE TITLE
Хэй, а тебя приняли то на работу?

### ISSUE THREAD

**Issue by koty166** [Tarveiz/Petrenko-Holtzman-method#1]

**Comment by Tarveiz** [comment]
Эм, а почему спрашиваешь?

**Comment by koty166** [comment]
Потому что у меня точно такое же тестовое.

**Comment by Tarveiz** [comment]
Ну нет, туда не взяли)

**Comment by koty166** [comment]
А чего так? В чём могут возникунуть проблемы?

**Comment by Tarveiz** [comment]
Ну, недостаток знаний, очевидно
